import type { Metadata } from "next";
import { site } from "@/lib/data/site";

export const metadata: Metadata = {
  title: "Terms of Service",
  description: `The terms for using the ${site.name} website, its free tools and its AI demos, and what happens when you request a build.`,
  alternates: { canonical: "/terms" },
};

/**
 * Accuracy pass 2026-08-30. The June 6 version described a website that had no
 * AI features, no free tools and no demo. It mentioned no processors, made no
 * statement about AI output, and said nothing about what the demo does and does
 * not do — while the site itself says "no real call, text, email or booking sent".
 *
 * Keep this page honest about three things the site is repeatedly tempted to
 * overstate: (1) submitting a form is a request, not a booking — there is no
 * calendar product (lib/data/site.ts bookingUrl); (2) listed prices are starting
 * points, and lib/data/packages.ts is the only source for them; (3) what the
 * customer owns at the end of a build is set by that project's written
 * agreement, not by a sentence on this page.
 */
const updated = "August 30, 2026";

export default function TermsPage() {
  return (
    <section className="relative pb-24 pt-32">
      <div className="mx-auto max-w-3xl px-4 sm:px-6">
        <span className="v-label">Legal</span>
        <h1 className="v-h1 mt-5 font-display">Terms of Service</h1>
        <p className="v-small mt-4">Last updated: {updated}</p>

        <div className="mt-10 space-y-10">
          <p className="v-lead">
            These terms cover your use of the {site.name} website, its free tools and its AI demos.
            Work we actually deliver is governed by a separate written proposal or agreement for that
            specific project; where the two differ, the project agreement wins.
          </p>

          <Section title="What this site is">
            <p>
              {site.name} is a one-person studio in {site.region}, Canada, run by {site.founder}. It
              designs and builds custom AI apps, agents, automations and business tools. The website
              describes that work, lets you try demonstrations of it, and lets you send a request.
            </p>
          </Section>

          <Section title="Sending a request is not a booking, and not a contract">
            <p>
              There is no calendar on this site and nothing here schedules a call. When you submit the
              form you are sending a written request. We aim to reply within one business day with a
              plan and a quote. No work begins, and nothing is owed by either side, until we agree on
              scope and price in writing.
            </p>
          </Section>

          <Section title="The AI demos">
            <p>
              The demonstrations on this site &mdash; the AI Worker Showroom, the AI interview, the
              product demos on the shop pages &mdash; are simulations. They never place a real call,
              send a real text message, send a real email on your behalf, or book anything with
              anyone.
            </p>
            <p>
              They are generated by a language model, so their output can be wrong, incomplete or
              plainly invented. Nothing a demo says is a quote, a commitment, or advice you should act
              on. Prices and timelines are only binding when we send them to you in writing.
            </p>
            <p>
              Please do not paste anything confidential, anyone else&apos;s personal information, or
              anything you would not want sent to a third-party AI provider into a demo. What happens
              to that text is described in our{" "}
              <a href="/privacy" className="v-link">
                Privacy Policy
              </a>
              .
            </p>
          </Section>

          <Section title="The free tools">
            <p>
              The calculators under <code>/tools</code> are planning aids. They run on the numbers you
              type, in your browser, using straightforward arithmetic. They are not financial,
              accounting, tax, legal or insurance advice, they do not know your business, and their
              output is an estimate. Check the result against your own books before you price a job
              with it.
            </p>
          </Section>

          <Section title="Quotes, prices and packages">
            <p>
              Prices, packages and timelines shown on this site are starting estimates in Canadian
              dollars, not binding quotes. The number that counts is the one in the written quote we
              send you after reading your request. Prices on the site can change without notice; a
              quote we have sent you does not.
            </p>
          </Section>

          <Section title="What you get at the end of a build">
            <p>
              What transfers to you at handover &mdash; the code, the accounts, the configuration, the
              phone number, the ongoing support &mdash; depends on what was built, and is set out in
              the written agreement for that project. Ask before you sign; we will put it in writing.
              Do not rely on a general statement on a marketing page for this.
            </p>
          </Section>

          <Section title="Using this site fairly">
            <ul>
              <li>Give accurate information when you contact us.</li>
              <li>
                Do not misuse the site, try to break it, scrape it at scale, or use it unlawfully.
              </li>
              <li>
                Do not use the AI demos to generate abusive, illegal or deceptive content, and do not
                try to extract our prompts or run automated traffic through them. They cost real money
                per request and are rate-limited; we may slow down or block traffic that abuses them,
                without notice.
              </li>
              <li>
                Content on this site &mdash; text, design, code, the {site.name} name and logo &mdash;
                belongs to us and may not be copied without permission.
              </li>
            </ul>
          </Section>

          <Section title="Accounts">
            <p>
              Parts of this site can require signing in with Google. Keep control of the account you
              sign in with; anything done through it is treated as done by you. We may suspend access
              to any signed-in area at any time. No subscription or payment is sold through this
              website today.
            </p>
          </Section>

          <Section title="No guarantees on the site">
            <p>
              The website is provided &ldquo;as is.&rdquo; We work to keep it accurate and available,
              but we do not guarantee it will be error-free, uninterrupted, or that every figure on it
              is current. Any third-party links are provided for convenience and are not our
              responsibility.
            </p>
          </Section>

          <Section title="Limitation of liability">
            <p>
              To the extent permitted by law, {site.name} is not liable for indirect or consequential
              losses arising from your use of this website, its free tools, or its demos. Nothing here
              limits liability that cannot be limited under applicable law, and nothing here changes
              the liability terms of a signed project agreement.
            </p>
          </Section>

          <Section title="Changes to these terms">
            <p>
              We update this page when the site changes, and the date at the top changes with it.
              Continuing to use the site after that means the updated terms apply.
            </p>
          </Section>

          <Section title="Governing law">
            <p>
              These terms are governed by the laws of British Columbia, Canada. Any dispute relating to
              the website will be handled in the courts of British Columbia.
            </p>
          </Section>

          <Section title="Contact">
            <p>
              Questions about these terms? Email{" "}
              <a href={`mailto:${site.email}`} className="v-link">
                {site.email}
              </a>
              .
            </p>
          </Section>
        </div>
      </div>
    </section>
  );
}

function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <div>
      <h2 className="v-h3 font-display">{title}</h2>
      <div className="v-body mt-3 space-y-3 [&_a]:font-medium [&_code]:text-[0.95em] [&_code]:text-ink [&_li]:ml-5 [&_li]:list-disc [&_strong]:text-ink [&_ul]:space-y-2">
        {children}
      </div>
    </div>
  );
}
